---
- name: Setup Mysql with accounts db and remote login
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Installing Mysql Service and dependencies
      package:
        name: "{{item}}" 
        state: present
        # why cache valid_time ?
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
      tags:
        - package

    - name: Start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
      tags:
        - svc

    - name: creating mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        # what kind of previlages and why that host
        priv: '*.*:ALL'
        host: '%'
        state: present


    - name: Creating accounts DB
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Enable remote login to mysql svc
      lineinfile:
      # where is this file and why backup and whats there in backup
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
      tags:
        - conf

 # why again restart       

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted