---
- name: Deploy SQL file on accounts db
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Copy SQL to dbsrv
      copy:
      # here why changing paths

        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      tags:
        - deploy

# what restoring db and why ??

    - name: Restoring DB
      mysql_db:
        name: "{{dbname}}"
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        state: import
        # here also why storing in tmp dir
        target: /tmp/db_backup.sql

      notify: 
        - Restart mysql
      tags:
        - deploy


  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
